### ISSUE TITLE
Unable to find where to put Google related stuff

### ISSUE THREAD

**Issue by Mach1neCoder** [Crabo-7498/vhhacks-2021#1]
Hey!  I love this concept, and I am working on a project that would really be able to utilize the code.  I am currently running a test, and notice that the google auth library says "could not load default credentials".  Is there a certain part of this code where I should be putting the credentials?  

Thanks in advance.

**Comment by jo3-l** [comment]
You should put your credentials in `credentials/google-credentials.json`.

Note, however, that you should really not run this code directly; frankly, I would be surprised if it runs at all. The primary issue is that the packages it uses are now outdated. Additionally, owing to its origins as a hackathon project, the code quality was not great to begin with. For these reasons, I would suggest using parts of the code as inspiration, but nothing more. (Of course, you are free to do whatever you wish as long as it conforms with the terms of our license.)

Hope that helps. Please reopen if you have a followup question.
